### ISSUE TITLE
App unavailable from MSFT Store

### ISSUE THREAD

**Issue by Neptune-mk2** [mcdenis/AccentApplicator#6]
I know this isn't really an issue related to anything code wise but I have no other way of contacting you, originally I hoped on emailing but I could not find a single email to contact you on the store page, so I resorted to posting here, so sorry in advance if this isn't considered a code related issue.

The store says the app is unavailable and its says it can only be downloaded by redeeming a code, is there a reason why this is happening? Did Microsoft de-list the app for some reason? I seem to only be able to download it through my library at the moment.

**Comment by ghost** [comment]
Same problem here

**Comment by mcdenis** [comment]
Thanks for reporting the issue and apologies for the late answer. So busy these days.

I have been suspecting of the app's unavailability for a few months, but I was not sure if it was only me, or if others were experiencing the same thing.

Last month, I was contacted by Microsoft regarding a compatibility issue they had found between Accent Applicator and the next stable release of Windows. I suspect it is the reason why the app was made unavailable. The issue in question has already been fixed, so hopefully the app will be available again soon. I will let you know when I know more.

**Comment by Neptune-mk2** [comment]
Ah good to know its comming back, and the app does work properly in the May 2019 update, I've been using it on release 1903 for a few weeks now it its works perfectly.

**Comment by Neptune-mk2** [comment]
Hi I know your probably very busy but the app is still unavailable and the May Update is rolling out publicly now.

I know some people that have been wanting to download that app but are still unable too
![image](https://user-images.githubusercontent.com/34612088/58590697-7e85c500-8219-11e9-8039-81d8ee670e45.png)

If your still having trouble with it I would recommend joining the UWP Community Discord server, lots of devs go around there and I think theres even a few MSFT Engineers there that might be able to help you get the incompatibility sorted out.

**Comment by mcdenis** [comment]
Thanks for the follow up. I have already advised Microsoft that the compatibility issue has been fixed, so I am really not sure what the problem could be. I have just checked the Developer Dashboard and it literally says that the app is "In the Store"… I will contact MS again and let you know when I know more.

**Comment by mcdenis** [comment]
Sorry folks, I give up! I have tried to get in touch with MS, but after a written back and forth with two people, I was ultimately told to call an 800 number, which is a no-go due to my incomprehensible oral English (it is not my first language).

I have tried many things in the hope to fix the problem by myself, but nothing seems to work and I just do not have any more time & energy to spend on this.

For now, I have created a new Github release with the .appk, so that you can install it manually.

**Comment by Arlodotexe** [comment]
Unfortunately, I'm getting this with the appx file 

![image](https://user-images.githubusercontent.com/9384894/60086278-6746d400-9700-11e9-8569-a2af13ac6c3a.png)

**Comment by Neptune-mk2** [comment]
> Sorry folks, I give up! I have tried to get in touch with MS, but after a written back and forth with two people, I was ultimately told to call an 800 number, which is a no-go due to my incomprehensible oral English (it is not my first language).
> 
> I have tried many things in the hope to fix the problem by myself, but nothing seems to work and I just do not have any more time & energy to spend on this.
> 
> For now, I have created a new Github release with the .appk, so that you can install it manually.

@mcdenis  Sorry for taking a while to reply but a lot of people over at the UWP Community discord sometimes encounter a issue where their app gets put in basically "Approval Hell", and the best solution when this happens is to simply submit the app with another name as a new store listing and hope for the best.

If you want some help figuring this out I recommend you join the UWP Community Discord, if I recall there is a few actual MSFT Engineers on there and some people with connections that might be able to get this resolved.

https://discordapp.com/invite/eBHZSKG

**Comment by mcdenis** [comment]
Thank you so much folks for your time and assistance on this issue. I wanted to try one last time to get in touch with MS before responding here, and guess what? I was finally able to reach to appropriate team and they were able to figure out the issue. **The app should now be available in the Store!**

![image](https://user-images.githubusercontent.com/25092585/61581756-523b4600-aaf0-11e9-862b-8060b30c110b.png)


However, I do not currently have access to a W10 machine to test it. Can anyone just confirm that it does indeed work?

**Comment by Neptune-mk2** [comment]
@mcdenis I was successfully able to install it on a system that didn't have it installed and it works!

Im going to mark this as closed in a bit but I'll leave it open just in case someone wants to comment something.

**Comment by mcdenis** [comment]
Wonderful, thank you! That is such a relief.
