### ISSUE TITLE
Windows on ARM64 version

### ISSUE THREAD

**Issue by james856** [mcdenis/AccentApplicator#7]
AccentApplicator currently runs as emulated x86 on Windows 10 on ARM64. Can you port the app to native ARM64 for better performance?

[Windows 10 ARM-based PCs FAQ](https://support.microsoft.com/en-us/help/4521606/windows-10-arm-based-pc)
[Surface Pro X app compatibility](https://docs.microsoft.com/en-us/surface/surface-pro-arm-app-performance)

**Comment by mcdenis** [comment]
Thanks for the suggestion. Unfortunately, I am no longer developing this app. As a replacement, I suggest [AccentColorizer](https://github.com/krlvm/AccentColorizer). I don't think it's available natively for ARM64, but since it's actively maintained, you might get lucky if you ask the developers.
